### ISSUE TITLE
NameError: name 'os' is not defined

### ISSUE THREAD

**Issue by ShahriyarR** [Percona-Lab/percona-autotokubackup#3]
Syntax error:
```
[root@tokubackup percona-autotokubackup]# tokubackup --backup
Traceback (most recent call last):
  File "/home/virtualenvs/py3_5_3_tokubackup/bin/tokubackup", line 11, in <module>
    load_entry_point('percona-autotokubackup==1.0', 'console_scripts', 'tokubackup')()
  File "/home/virtualenvs/py3_5_3_tokubackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/virtualenvs/py3_5_3_tokubackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/virtualenvs/py3_5_3_tokubackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/virtualenvs/py3_5_3_tokubackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/virtualenvs/py3_5_3_tokubackup/lib/python3.5/site-packages/percona_autotokubackup-1.0-py3.5.egg/tokubackup.py", line 62, in all_procedure
  File "/home/virtualenvs/py3_5_3_tokubackup/lib/python3.5
```

**Comment by ShahriyarR** [comment]
Another one:

```
[root@tokubackup percona-autotokubackup]# tokubackup --backup
Traceback (most recent call last):
  File "/home/virtualenvs/py3_5_3_tokubackup/bin/tokubackup", line 11, in <module>
    load_entry_point('percona-autotokubackup==1.0', 'console_scripts', 'tokubackup')()
  File "/home/virtualenvs/py3_5_3_tokubackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/virtualenvs/py3_5_3_tokubackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/virtualenvs/py3_5_3_tokubackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/virtualenvs/py3_5_3_tokubackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/virtualenvs/py3_5_3_tokubackup/lib/python3.5/site-packages/percona_autotokubackup-1.0-py3.5.egg/tokubackup.py", line 63, in all_procedure
  File "/home/virtualenvs/py3_5_3_tokubackup/lib/python3.5/site-packages/percona_autotokubackup-1.0-py3.5.egg/tokubackup.py", line 43, in validate_file
NameError: name 're' is not defined

```
